[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "cocotb-TileLink"
dynamic = ["version"]
requires-python = ">=3.5"
dependencies = [
    "cocotb >= 2.0.0",
    "cocotb-bus @ git+https://github.com/cocotb/cocotb-bus.git@6ab25ec7bd03e834a8770503bfadec084f69b6a3",
]

authors = [
    {name="Antmicro"},
]

description = "TileLink cocotb drivers"
readme = "README.md"

keywords = ["cocotb", "TileLink"]

[project.urls]
Source = "https://github.com/antmicro/cocotb-tilelink"
Tracker = "https://github.com/antmicro/cocotb-tilelink/issues"
Changelog = "https://github.com/antmicro/cocotbext-i3c/releases"

[tool.setuptools.dynamic]
version = {attr = "cocotb_TileLink._version.__version__"}
